ALTER TABLE FOODS
ADD COLUMN CARB_TYPE VARCHAR(50);

UPDATE FOODS
SET CARB_TYPE = "Complex"
WHERE FOOD_ID IN (1,2,3,4);

ALTER TABLE FOODS
DROP COLUMN CARB_TYPE;

DELETE FROM FOODS
WHERE FOOD_ID = 4;

DROP TABLE NUTRIENTS;

DROP TABLE FOODS;

DROP SCHEMA FOOD_SCHEMA;