CREATE DATABASE `FOOD_SCHEMA`;

CREATE TABLE `FOODS` (
FOOD_ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
COLOR VARCHAR(100) NOT NULL,
NUTRIENT VARCHAR(20) NOT NULL,
TYPE VARCHAR(150),
NUMBER_PRODUCED INT,
RECORD_CREATED TIMESTAMP,
PRIMARY KEY ( FOOD_ID )
);

INSERT INTO FOODS
(NAME, COLOR, NUTRIENT, TYPE, NUMBER_PRODUCED, RECORD_CREATED)
VALUES ("Nectarine", "Orange", "Vitamin C", "Fruit", 1, NOW());

INSERT INTO FOODS
(NAME, COLOR, NUTRIENT, TYPE, NUMBER_PRODUCED, RECORD_CREATED)
VALUES ("Banana", "Yellow", "Potassium", "Fruit", 6, NOW());

INSERT INTO FOODS
(NAME, COLOR, NUTRIENT, TYPE, NUMBER_PRODUCED, RECORD_CREATED)
VALUES ("Mushroom", "Tan", "Vitamin B-12", "Fungus", 4, NOW());

INSERT INTO FOODS
(NAME, COLOR, NUTRIENT, TYPE, NUMBER_PRODUCED, RECORD_CREATED)
VALUES ("Cucumber", "Green", "Zinc", "Vegetable", 1, NOW());

CREATE TABLE `NUTRIENTS` (
NUTRIENT_ID INT NOT NULL  AUTO_INCREMENT,
NUTRIENT VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(200) NOT NULL,
REC_DOSE_MG INT,
RECORD_CREATED TIMESTAMP,
PRIMARY KEY (NUTRIENT_ID )
);

INSERT INTO NUTRIENTS
(NUTRIENT, DESCRIPTION, REC_DOSE_MG, RECORD_CREATED)
VALUES ("Potassium", "Helps maintain proper and healthy blood pressure.", 4700, NOW());

INSERT INTO NUTRIENTS
(NUTRIENT, DESCRIPTION, REC_DOSE_MG, RECORD_CREATED)
VALUES ("Zinc", "Helps maintain proper cell growth and regeneration.", 11, NOW());

INSERT INTO NUTRIENTS
(NUTRIENT, DESCRIPTION, REC_DOSE_MG, RECORD_CREATED)
VALUES ("Vitamin C", "Helps boost the body's immune system.", 90, NOW());

INSERT INTO NUTRIENTS
(NUTRIENT, DESCRIPTION, REC_DOSE_MG, RECORD_CREATED)
VALUES ("Vitamin B-12", "Essential for converting food into energy and aiding in the digestion process for proper absorption of nutrients.", 1, NOW());

SELECT * FROM NUTRIENTS;

